#!/bin/sh

echo Running bash script in github

#export CHAIN_ID=namada.5f5de2dd1b88cba30586420
#export NAMADA_NETWORK_CONFIGS_SERVER="https://github.com/anoma/namada-mainnet-genesis/releases/download/mainnet-genesis"
#namada --version
#echo "Joining Namada Network"
#namadac utils join-network --chain-id $CHAIN_ID

export VALIDATOR_ADDRESS=tnam1qyvc8n7ufmpan4yy3nemm3td2c6uff4m6s72g3eg


echo "fetching the validator commission"
COMMISSION=$(curl -s https://api.namada.valopers.com/account/$VALIDATOR_ADDRESS/commission | jq -r .amount)

DETAILS=$(curl -s https://api.namada.valopers.com/validators/details/$VALIDATOR_ADDRESS)
STAKEM=$(echo $DETAILS | jq -r .stake)
STAKE=$(echo "scale=2;$STAKEM / 1000000" | bc)
COMMISSION_RATE=$(echo $DETAILS | jq -r .commission.commission_rate)

METRIC_FILE=metrics/metrics.txt

start_time=$(date +%s)

last_run=$(curl -s https://shield-crypto.github.io/validator-rewards/last_run.txt)
elapsed=$((start_time - $last_run))
fraction_year=$(echo "scale=8;$elapsed / 31536000"  | bc)

echo "# HELP shield_time_period Fraction of the year represented by this calculation " > $METRIC_FILE
echo "# TYPE shield_time_period gauge" >> $METRIC_FILE
echo "shield_time_period $fraction_year" >> $METRIC_FILE


echo "# HELP shield_validator_commission_rate Commission Rate for the validator" >> $METRIC_FILE
echo "# TYPE shield_validator_commission_rate gauge" >> $METRIC_FILE
echo "shield_validator_commission_rate $COMMISSION_RATE" >> $METRIC_FILE

echo "# HELP shield_validator_stake Stake on the validator" >> $METRIC_FILE
echo "# TYPE shield_validator_stake gauge" >> $METRIC_FILE
echo "shield_validator_stake $STAKE" >> $METRIC_FILE

echo "# HELP shield_validator_rewards rewards generated by the validator" >> $METRIC_FILE
echo "# TYPE shield_validator_rewards gauge" >> $METRIC_FILE
echo "shield_validator_rewards $COMMISSION" >> $METRIC_FILE

rewards_delegators=$(echo "scale=2; $COMMISSION / $COMMISSION_RATE" | bc)

echo "# HELP shield_delegators_rewards rewards distributed to delegators" >> $METRIC_FILE
echo "# TYPE shield_delegators_rewards gauge" >> $METRIC_FILE
echo "shield_delegators_rewards $rewards_delegators" >> $METRIC_FILE


rewards_percentage_delegators=$(echo "scale=10; $rewards_delegators / $STAKE" | bc)

echo "# HELP shield_delegators_rewards_percentage Percentage of rewards vs staked amount on the validator" >> $METRIC_FILE
echo "# TYPE shield_delegators_rewards_percentage gauge" >> $METRIC_FILE
echo "shield_delegators_rewards_percentage $rewards_percentage_delegators" >> $METRIC_FILE

# APR = (1 + rewards_percentage_delegators)^(1/fraction_year)-1

#APR=$(echo "scale=8;(1+$rewards_percentage_delegators)^(1/$fraction_year)-1" | bc)
echo $start_time > metrics/last_run.txt

echo "# HELP shield_delegators_apy APY generated for delegators by the validator" >> $METRIC_FILE
echo "# TYPE shield_delegators_apyv gauge" >> $METRIC_FILE
echo "shield_delegators_apy 20" >> $METRIC_FILE

